export default {
  key: "vacancies",
  title: "Vacantes",
  singular: "Vacante",
  route: "#/vacantes",
  endpoint: "/products",
  createEndpoint: "/products/add",
  responseKey: "products",
  methods: {
    create: "POST",
    replace: "PUT",
    update: "PATCH",
    remove: "DELETE",
  },
  searchableFields: ["title", "description", "category", "brand"],
  tableColumns: [
    { key: "title", label: "Puesto" },
    { key: "description", label: "Descripción" },
    { key: "category", label: "Área" },
    { key: "price", label: "Salario de referencia" },
    { key: "stock", label: "Plazas disponibles" },
    { key: "brand", label: "Empresa" },
  ],
  formFields: [
    {
      name: "title",
      label: "Puesto",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Ej. Desarrollador Front End",
    },
    {
      name: "description",
      label: "Descripción",
      type: "textarea",
      required: true,
      minLength: 10,
      maxLength: 500,
      rows: 5,
      placeholder: "Describe las responsabilidades principales de la vacante",
    },
    {
      name: "category",
      label: "Área",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 80,
      placeholder: "Ej. Tecnología",
    },
    {
      name: "price",
      label: "Salario de referencia",
      type: "number",
      required: true,
      min: 1,
      max: 100000000,
      placeholder: "Ej. 850000",
    },
    {
      name: "stock",
      label: "Plazas disponibles",
      type: "number",
      required: true,
      min: 1,
      max: 10000,
      placeholder: "Ej. 2",
    },
    {
      name: "brand",
      label: "Empresa",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Ej. JobConnect Labs",
    },
  ],
};
