export default {
  key: "companies",
  title: "Empresas clientes",
  singular: "Empresa cliente",
  route: "#/empresas",
  endpoint: "/carts",
  createEndpoint: "/carts/add",
  responseKey: "carts",
  methods: {
    create: "POST",
    replace: "PUT",
    update: null,
    remove: "DELETE",
  },
  searchableFields: ["userId", "vacancyId", "totalProducts", "totalQuantity", "total"],
  tableColumns: [
    { key: "userId", label: "ID del contacto" },
    { key: "vacancyId", label: "ID de la vacante" },
    { key: "totalProducts", label: "Vacantes vinculadas" },
    { key: "totalQuantity", label: "Posiciones totales" },
    { key: "total", label: "Presupuesto estimado" },
  ],
  formFields: [
    {
      name: "userId",
      label: "ID del contacto de la empresa",
      type: "number",
      required: true,
      min: 1,
      max: 1000000,
      placeholder: "Ej. 12",
    },
    {
      name: "vacancyId",
      label: "ID de la vacante",
      type: "number",
      required: true,
      min: 1,
      max: 1000000,
      placeholder: "Ej. 4",
    },
    {
      name: "quantity",
      label: "Cantidad de posiciones",
      type: "number",
      required: true,
      min: 1,
      max: 10000,
      placeholder: "Ej. 2",
    },
  ],
};
