export default {
  key: "interviews",
  title: "Entrevistas",
  singular: "Entrevista",
  route: "#/entrevistas",
  endpoint: "/comments",
  createEndpoint: "/comments/add",
  responseKey: "comments",
  methods: {
    create: "POST",
    replace: null,
    update: "PATCH",
    remove: "DELETE",
  },
  searchableFields: ["body", "postId", "userId"],
  tableColumns: [
    { key: "body", label: "Notas" },
    { key: "postId", label: "ID de postulación" },
    { key: "userId", label: "ID del reclutador" },
    {
      key: "user",
      label: "Reclutador",
      render: (record) => record.user?.fullName ?? "—",
    },
    { key: "likes", label: "Seguimientos" },
  ],
  formFields: [
    {
      name: "body",
      label: "Notas",
      type: "textarea",
      required: true,
      minLength: 5,
      maxLength: 500,
      rows: 5,
      placeholder: "Registra las notas principales de la entrevista",
    },
    {
      name: "postId",
      label: "ID de postulación",
      type: "number",
      required: true,
      min: 1,
      max: 1000000,
      placeholder: "Ej. 15",
    },
    {
      name: "userId",
      label: "ID del reclutador",
      type: "number",
      required: true,
      min: 1,
      max: 1000000,
      placeholder: "Ej. 1",
    },
  ],
};
