export default {
  key: "applications",
  title: "Postulaciones",
  singular: "Postulación",
  route: "#/postulaciones",
  endpoint: "/posts",
  createEndpoint: "/posts/add",
  responseKey: "posts",
  methods: {
    create: "POST",
    replace: null,
    update: "PATCH",
    remove: "DELETE",
  },
  searchableFields: ["title", "body", "userId", "tags"],
  tableColumns: [
    { key: "title", label: "Puesto solicitado" },
    { key: "body", label: "Resumen de la postulación" },
    { key: "userId", label: "ID del candidato" },
    {
      key: "tags",
      label: "Etiquetas o estado del proceso",
      render: (record) => (Array.isArray(record.tags) ? record.tags.join(", ") : record.tags),
    },
    {
      key: "reactions",
      label: "Valoración positiva",
      render: (record) => record.reactions?.likes ?? 0,
    },
  ],
  formFields: [
    {
      name: "title",
      label: "Puesto solicitado",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Ej. Desarrollador Front End",
    },
    {
      name: "body",
      label: "Resumen de la postulación",
      type: "textarea",
      required: true,
      minLength: 10,
      maxLength: 500,
      rows: 5,
      placeholder: "Resume la postulación del candidato",
    },
    {
      name: "userId",
      label: "ID del candidato",
      type: "number",
      required: true,
      min: 1,
      max: 1000000,
      placeholder: "Ej. 12",
    },
    {
      name: "tags",
      label: "Etiquetas o estado del proceso",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 160,
      placeholder: "Ej. nuevo, revisión, técnico",
    },
  ],
};
