export default {
  key: "candidates",
  title: "Candidatos",
  singular: "Candidato",
  route: "#/candidatos",
  endpoint: "/users",
  createEndpoint: "/users/add",
  responseKey: "users",
  methods: {
    create: "POST",
    replace: "PUT",
    update: "PATCH",
    remove: "DELETE",
  },
  searchableFields: ["firstName", "lastName", "email", "phone", "companyName", "companyTitle"],
  tableColumns: [
    { key: "image", label: "Foto", type: "image" },
    { key: "firstName", label: "Nombre" },
    { key: "lastName", label: "Apellidos" },
    { key: "email", label: "Correo" },
    { key: "phone", label: "Teléfono" },
    { key: "age", label: "Edad" },
    { key: "companyName", label: "Empresa" },
    { key: "companyTitle", label: "Puesto actual" },
  ],
  formFields: [
    {
      name: "firstName",
      label: "Nombre",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 80,
      placeholder: "Ej. Ana",
    },
    {
      name: "lastName",
      label: "Apellidos",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 100,
      placeholder: "Ej. Rodríguez Mora",
    },
    {
      name: "email",
      label: "Correo",
      type: "email",
      required: true,
      maxLength: 160,
      placeholder: "ana@correo.com",
    },
    {
      name: "phone",
      label: "Teléfono",
      type: "tel",
      required: true,
      minLength: 8,
      maxLength: 30,
      placeholder: "Ej. 8888-8888",
    },
    {
      name: "age",
      label: "Edad",
      type: "number",
      required: true,
      min: 18,
      max: 100,
      placeholder: "Ej. 28",
    },
  ],
};
